# Generated by Django 6.0.7 on 2026-07-08 14:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('fonts', models.JSONField(blank=True, default=list)),
                ('design_system', models.JSONField(blank=True, default=dict)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('crawl_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scraped/')),
                ('label', models.CharField(choices=[('logo', 'Logo'), ('product', 'Product'), ('photo', 'Photo'), ('icon', 'Icon'), ('other', 'Other')], default='other', max_length=20)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='brandgen.brand')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X / Twitter')], default='linkedin', max_length=20)),
                ('post_type', models.CharField(choices=[('single', 'Single image'), ('carousel', 'Carousel'), ('quote', 'Quote card')], default='single', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('approved', 'Approved'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('slide_count', models.PositiveSmallIntegerField(default=1)),
                ('prompt_meta', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='brandgen.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('headline', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='generated/')),
                ('generation_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='brandgen.socialpost')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
