# Generated by Django 6.0.7 on 2026-07-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandgen', '0002_pipelinejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='postslide',
            name='ocr_reason',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='postslide',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postslide',
            name='overlay_mode',
            field=models.CharField(blank=True, default='', help_text='How typography was applied: logo_only | headline_overlay | regenerated_no_text', max_length=40),
        ),
    ]
