# Generated by Django 6.0.7 on 2026-07-08 22:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandgen', '0003_postslide_ocr_reason_postslide_ocr_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_session', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('crawl_started', 'Crawl started'), ('crawl_completed', 'Crawl completed'), ('crawl_failed', 'Crawl failed'), ('generate_started', 'Generate started'), ('generate_completed', 'Generate completed'), ('generate_failed', 'Generate failed'), ('post_approved', 'Post approved'), ('post_skipped', 'Post skipped'), ('regenerate_started', 'Regenerate started'), ('refine_started', 'Refine started'), ('api_key_set', 'Visitor API key set'), ('api_key_cleared', 'Visitor API key cleared'), ('slide_download', 'Slide downloaded')], db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('billing_mode', models.CharField(choices=[('user', 'Visitor key'), ('demo', 'Demo / server key'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('website_domain', models.CharField(blank=True, db_index=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brandgen.brand')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brandgen.pipelinejob')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brandgen.socialpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'event_type'], name='brandgen_us_created_db32fb_idx'), models.Index(fields=['website_domain', '-created_at'], name='brandgen_us_website_ffb1b3_idx')],
            },
        ),
    ]
