# Generated by Django 6.0.7 on 2026-07-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandgen', '0004_usageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_enabled', models.BooleanField(default=True, help_text='When enabled, OCR checks AI-rendered text and may overlay headlines. When disabled, images are generated without text and only the brand logo is composited.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pipeline settings',
                'verbose_name_plural': 'Pipeline settings',
            },
        ),
    ]
